# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class ClosestAbbreviation(BaseModel):
    original: typing.Optional[str] = None
    closest: typing.Optional[str] = None
    confidence: typing.Optional[str] = None
    decoding: typing.Dict[str, str]
    reasoning: typing.Optional[str] = None

class GeneratedQuestion(BaseModel):
    question_number: typing.Optional[int] = None
    question: typing.Optional[str] = None
    options: typing.List["QuestionOption"]
    answer: typing.List[str]
    explanation: typing.Optional[str] = None

class QuestionGenerationResult(BaseModel):
    questions: typing.List["GeneratedQuestion"]
    teaching_point: typing.Optional[str] = None
    question_type: typing.Optional[str] = None
    language: typing.Optional[str] = None
    bloom_level: typing.Optional[str] = None

class QuestionOption(BaseModel):
    key: typing.Optional[str] = None
    value: typing.Optional[str] = None

class TeachingMaterial(BaseModel):
    text_en: typing.Optional[str] = None
    text_ar: typing.Optional[str] = None
    context: typing.Optional[str] = None

class WeatherAPI(BaseModel):
    city: typing.Optional[str] = None
    timeOfDay: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
