# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def DecodeMilitaryAbbreviations(self, material: types.TeachingMaterial,
        baml_options: BamlCallOptions = {},
    ) -> types.ClosestAbbreviation:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="DecodeMilitaryAbbreviations", args={
            "material": material,
        })
        return typing.cast(types.ClosestAbbreviation, result.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateQuestions(self, teaching_point_en: str,teaching_point_ar: str,context: typing.Optional[str],question_type: str,number_of_distractors: typing.Optional[int],number_of_correct_answers: typing.Optional[int],language: str,bloom_level: str,
        baml_options: BamlCallOptions = {},
    ) -> types.QuestionGenerationResult:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateQuestions", args={
            "teaching_point_en": teaching_point_en,"teaching_point_ar": teaching_point_ar,"context": context,"question_type": question_type,"number_of_distractors": number_of_distractors,"number_of_correct_answers": number_of_correct_answers,"language": language,"bloom_level": bloom_level,
        })
        return typing.cast(types.QuestionGenerationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def UseTool(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> types.WeatherAPI:
        result = self.__options.merge_options(baml_options).call_function_sync(function_name="UseTool", args={
            "user_message": user_message,
        })
        return typing.cast(types.WeatherAPI, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DecodeMilitaryAbbreviations(self, material: types.TeachingMaterial,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ClosestAbbreviation, types.ClosestAbbreviation]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="DecodeMilitaryAbbreviations", args={
            "material": material,
        })
        return baml_py.BamlSyncStream[stream_types.ClosestAbbreviation, types.ClosestAbbreviation](
          result,
          lambda x: typing.cast(stream_types.ClosestAbbreviation, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClosestAbbreviation, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateQuestions(self, teaching_point_en: str,teaching_point_ar: str,context: typing.Optional[str],question_type: str,number_of_distractors: typing.Optional[int],number_of_correct_answers: typing.Optional[int],language: str,bloom_level: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.QuestionGenerationResult, types.QuestionGenerationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateQuestions", args={
            "teaching_point_en": teaching_point_en,"teaching_point_ar": teaching_point_ar,"context": context,"question_type": question_type,"number_of_distractors": number_of_distractors,"number_of_correct_answers": number_of_correct_answers,"language": language,"bloom_level": bloom_level,
        })
        return baml_py.BamlSyncStream[stream_types.QuestionGenerationResult, types.QuestionGenerationResult](
          result,
          lambda x: typing.cast(stream_types.QuestionGenerationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QuestionGenerationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def UseTool(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.WeatherAPI, types.WeatherAPI]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="UseTool", args={
            "user_message": user_message,
        })
        return baml_py.BamlSyncStream[stream_types.WeatherAPI, types.WeatherAPI](
          result,
          lambda x: typing.cast(stream_types.WeatherAPI, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.WeatherAPI, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DecodeMilitaryAbbreviations(self, material: types.TeachingMaterial,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DecodeMilitaryAbbreviations", args={
            "material": material,
        }, mode="request")
        return result
    def GenerateQuestions(self, teaching_point_en: str,teaching_point_ar: str,context: typing.Optional[str],question_type: str,number_of_distractors: typing.Optional[int],number_of_correct_answers: typing.Optional[int],language: str,bloom_level: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateQuestions", args={
            "teaching_point_en": teaching_point_en,"teaching_point_ar": teaching_point_ar,"context": context,"question_type": question_type,"number_of_distractors": number_of_distractors,"number_of_correct_answers": number_of_correct_answers,"language": language,"bloom_level": bloom_level,
        }, mode="request")
        return result
    def UseTool(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="UseTool", args={
            "user_message": user_message,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DecodeMilitaryAbbreviations(self, material: types.TeachingMaterial,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DecodeMilitaryAbbreviations", args={
            "material": material,
        }, mode="stream")
        return result
    def GenerateQuestions(self, teaching_point_en: str,teaching_point_ar: str,context: typing.Optional[str],question_type: str,number_of_distractors: typing.Optional[int],number_of_correct_answers: typing.Optional[int],language: str,bloom_level: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateQuestions", args={
            "teaching_point_en": teaching_point_en,"teaching_point_ar": teaching_point_ar,"context": context,"question_type": question_type,"number_of_distractors": number_of_distractors,"number_of_correct_answers": number_of_correct_answers,"language": language,"bloom_level": bloom_level,
        }, mode="stream")
        return result
    def UseTool(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="UseTool", args={
            "user_message": user_message,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))