# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClosestAbbreviation": types.ClosestAbbreviation,
    "stream_types.ClosestAbbreviation": stream_types.ClosestAbbreviation,

    "types.GeneratedQuestion": types.GeneratedQuestion,
    "stream_types.GeneratedQuestion": stream_types.GeneratedQuestion,

    "types.QuestionGenerationResult": types.QuestionGenerationResult,
    "stream_types.QuestionGenerationResult": stream_types.QuestionGenerationResult,

    "types.QuestionOption": types.QuestionOption,
    "stream_types.QuestionOption": stream_types.QuestionOption,

    "types.TeachingMaterial": types.TeachingMaterial,
    "stream_types.TeachingMaterial": stream_types.TeachingMaterial,

    "types.WeatherAPI": types.WeatherAPI,
    "stream_types.WeatherAPI": stream_types.WeatherAPI,


}